language: php

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.18.0
  matrix:
    - PHP_VERSION=7.1 DRUPAL_CORE=8.5.0-rc1 DEPENDENCIES="--prefer-lowest"
    - PHP_VERSION=7.1 DRUPAL_CORE=8.5.0-rc1 DEPENDENCIES=""
    - PHP_VERSION=7.1 DRUPAL_CORE=8.5.x-dev DEPENDENCIES="--prefer-lowest"

matrix:
  allow_failures:
    - env: PHP_VERSION=7.1 DRUPAL_CORE=8.5.x-dev DEPENDENCIES="--prefer-lowest"

# TODO Cache Docker images and PHP service build (common parts of the built, like Drupal core install, for a day).
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose pull
  - docker-compose build php
  - docker-compose up -d
  - docker-compose ps

script:
  - set -e
# Do not report warnings (like Drupal.Semantics.FunctionT.NotLiteralString) on Travis CI. Use selective disabling
# when Drupal Coder will support PHPCS >= 3.2.0.
# https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file
  - docker-compose run phpcs -s -n --colors --standard=/opt/drupal-module/phpcs.xml.dist /opt/drupal-module
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker-compose run php sh /opt/drupal-module/test.sh; fi
