language: php

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.18.0
  matrix:
    - DRUPAL_CORE=8.4 DEPENDENCIES="--prefer-lowest"
    - DRUPAL_CORE=8.4 DEPENDENCIES=""

#matrix:
#  allow_failures:
#    - env: DRUPAL_CORE=8.5 DEPENDENCIES="--prefer-lowest"
#    - env: DRUPAL_CORE=8.5 DEPENDENCIES=""

# TODO Cache Docker images and PHP service build (common parts of the built, like Drupal core install, for a day).
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose pull
  - COMPOSE_PROJECT_NAME="apigee-edge-${DRUPAL_CORE}-${DEPENDENCIES}" docker-compose build php
  - COMPOSE_PROJECT_NAME="apigee-edge-${DRUPAL_CORE}-${DEPENDENCIES}" docker-compose up -d
  - docker ps -a

script:
  - set -e
  - COMPOSE_PROJECT_NAME="apigee-edge-${DRUPAL_CORE}-${DEPENDENCIES}" docker-compose run --user 82 php sh /opt/drupal-module/test.sh
