version: "3"

services:
  php:
    environment:
      # We can not pass these environment variables with `docker-compose run -e` until
      # this has not been improved. https://github.com/wodby/php/pull/21#issuecomment-361200733
      DRUPAL_MODULE_NAME: apigee_edge
      APIGEE_EDGE_ENDPOINT: ${APIGEE_EDGE_ENDPOINT}
      APIGEE_EDGE_USERNAME: ${APIGEE_EDGE_USERNAME}
      APIGEE_EDGE_PASSWORD: ${APIGEE_EDGE_PASSWORD}
      APIGEE_EDGE_ORGANIZATION: ${APIGEE_EDGE_ORGANIZATION}
      APIGEE_EDGE_TEST_LOG_FILE: "/mnt/files/apigee_edge_debug.log"
      # Suppress deprecation warnings.
      # https://api.drupal.org/api/drupal/vendor%21symfony%21phpunit-bridge%21DeprecationErrorHandler.php/8.5.x
      SYMFONY_DEPRECATIONS_HELPER: disabled
