apigee_edge.error_page:
  type: config_object
  mapping:
    error_page_title:
      type: string
    error_page_content:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text

apigee_edge.authentication_method:
  type: config_object
  mapping:
    authentication_method:
      type: string

apigee_edge.credentials_storage:
  type: config_object
  mapping:
    credentials_storage_type:
      type: string

apigee_edge.entity_labels:
  type: config_object
  mapping:
    app_label_singular:
      type: string
    app_label_plural:
      type: string
    api_product_label_singular:
      type: string
    api_product_label_plural:
      type: string

apigee_edge.appsettings:
  type: config_object
  mapping:
    display_as_select:
      type: boolean
    associate_apps:
      type: boolean
    user_select:
      type: boolean
    multiple_products:
      type: boolean
    require:
      type: boolean
    description_visible:
      type: boolean
    description_required:
      type: boolean
    callback_url_visible:
      type: boolean
    callback_url_required:
      type: boolean
    default_products:
      type: sequence
      sequence:
        type: string

apigee_edge.sync:
  type: config_object
  mapping:
    filter:
      type: string
