apigee_edge.error_page:
  type: config_object
  mapping:
    error_page_title:
      type: string
    error_page_content:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text

apigee_edge.authentication:
  type: config_object
  mapping:
    active_key:
      type: string
    default_endpoint:
      type: string

apigee_edge.entity_labels:
  type: config_object
  mapping:
    app_label_singular:
      type: string
    app_label_plural:
      type: string
    api_product_label_singular:
      type: string
    api_product_label_plural:
      type: string

apigee_edge.appsettings:
  type: config_object
  mapping:
    display_as_select:
      type: boolean
    associate_apps:
      type: boolean
    user_select:
      type: boolean
    multiple_products:
      type: boolean
    require:
      type: boolean
    required_base_fields:
      type: sequence
      sequence:
        type: string
    locked_base_fields:
      type: sequence
      sequence:
        type: string
    default_products:
      type: sequence
      sequence:
        type: string
    cache_expiration:
      type: integer

apigee_edge.developer_settings:
  type: config_object
  mapping:
    verification_action:
      type: string
    display_only_error_message_content:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text
    verify_email_error_message:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text
    verification_email_subject:
      type: string
    verification_email_content:
      type: text
    verification_token:
      type: string
    verification_token_expires:
      type: integer
    user_edit_error_message:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text
    cache_expiration:
      type: integer

apigee_edge.api_product_settings:
  type: config_object
  mapping:
    cache_expiration:
      type: integer

apigee_edge.sync:
  type: config_object
  mapping:
    filter:
      type: string

key.type.apigee_edge_basic_auth:
  type: sequence

key.input.apigee_edge_basic_auth_input:
  type: sequence

key.provider.apigee_edge_basic_auth_env_variables:
  type: sequence

key.provider.apigee_edge_basic_auth_private_file:
  type: sequence
