apigee_edge.error_page:
  type: config_object
  label: 'Apigee Edge: Error page'
  mapping:
    error_page_title:
      type: label
      label: 'Error page title'
    error_page_content:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text
          label: 'Error page content'

apigee_edge.client:
  type: config_object
  mapping:
    active_key:
      type: string
    active_key_oauth_token:
      type: string
    http_client_timeout:
      type: integer
    http_client_proxy:
      type: string

apigee_edge.common_app_settings:
  type: config_object
  label: 'Common app settings'
  mapping:
    display_as_select:
      type: boolean
    associate_apps:
      type: boolean
    user_select:
      type: boolean
    multiple_products:
      type: boolean
    require:
      type: boolean
    required_base_fields:
      type: sequence
      sequence:
        type: string
    locked_base_fields:
      type: sequence
      sequence:
        type: string
    default_products:
      type: sequence
      sequence:
        type: string
    analytics_environment:
      type: string

apigee_edge.developer_app_settings:
  type: config_object
  label: 'Developer app settings'
  mapping:
    entity_label_singular:
      type: label
      label: 'How to refer to a Developer App on the UI (singular)'
    entity_label_plural:
      type: label
      label: 'How to refer to a Developer App on the UI (plural)'
    cache_expiration:
      type: integer

apigee_edge.developer_settings:
  type: config_object
  label: 'Developer settings'
  mapping:
    verification_action:
      type: string
    display_only_error_message_content:
      type: mapping
      label: 'Error message when a new user registers and the developer email address is already taken on Edge but not in Drupal'
      mapping:
        format:
          type: string
        value:
          type: text
          label: 'Message'
    verify_email_error_message:
      type: mapping
      mapping:
        format:
          type: string
        value:
          type: text
    verification_email:
      type: 'mail'
      label: 'Verification email'
    verification_token:
      type: string
    verification_token_expires:
      type: integer
    user_edit_error_message:
      type: mapping
      label: 'Error message displayed to a user when the email address is already taken on Edge but not in Drupal'
      mapping:
        format:
          type: string
        value:
          type: text
          label: 'Message'
    cache_expiration:
      type: integer

apigee_edge.api_product_settings:
  type: config_object
  label: 'API Product settings'
  mapping:
    entity_label_singular:
      type: label
      label: 'How to refer to an API Product on the UI (singular)'
    entity_label_plural:
      type: label
      label: 'How to refer to an API Product on the UI (plural)'
    cache_expiration:
      type: integer

apigee_edge.sync:
  type: config_object
  mapping:
    filter:
      type: string
    user_fields_to_sync:
      type: sequence
      sequence:
        type: string

key.type.apigee_edge_basic_auth:
  type: sequence

key.type.apigee_edge_oauth:
  type: sequence

key.type.apigee_edge_oauth_token:
  type: sequence

key.input.apigee_edge_basic_auth_input:
  type: sequence

key.input.apigee_edge_oauth_input:
  type: sequence

key.provider.apigee_edge_environment_variables:
  type: sequence

key.provider.apigee_edge_private_file:
  type: sequence
