apigee_edge_apiproduct_rbac.settings:
  type: config_object
  mapping:
    attribute_name:
      type: string
      label: 'Attribute name'
    grant_access_if_attribute_missing:
      type: sequence
      label: 'Grant access to the following roles if attribute is missing'
      sequence:
        label: 'Roles with access'
        type: string
