apigee_edge.authentication_method:
  type: config_object
  mapping:
    authentication_method:
      type: string

apigee_edge.credentials_storage:
  type: config_object
  mapping:
    credentials_storage_type:
      type: string

apigee_edge.createapp:
  type: config_object
  mapping:
    multiple_products:
      type: boolean
    display_as_checkboxes:
      type: boolean
    description_visible:
      type: boolean
    description_required:
      type: boolean
    callback_url_visible:
      type: boolean
    callback_url_required:
      type: boolean
